### ISSUE TITLE
Ergonomics

### ISSUE THREAD

**Issue by mildred** [frappe/books#798]
Interface in general

- [x] #1026 : Sidebar vertical scroll on small screens
- [x] #810 Add ability to save list item views, available in the left navigation tree, persist filters
- [ ] Add ability to save reports, available in the left navigation tree, persist filters
- [x] #1028 : Ability to view PDF files (either in native viewer or inside the app) without having to download them

Reports / Journal Entries

- [ ] Allow to have any value in the journal entry type of entry
- [ ] In the list, add column to show total amount for the journal entry
- [ ] Add a column for the debit account(s) and the credit account(s)
- [ ] Allow to configure visible columns

Balance sheet / Profit and Losses

- [ ] click on a row show the general ledger filtered for that specific account
- [x] #1032 : show opening entries
- [x] #1032 : show closing (opening entries + current entries)

General Ledger

- [x] #1031 : Better selection of time period
- [x] #1029 : Show opening balances in general ledger
- [ ] Allow to configure visible columns
- [ ] If a group account is selected, show ledger entries for sub-accounts too
- [ ] Add column to show total account balance at this point in time
- [ ] Click on the ref should redirect to the item
- [ ] Click on the row should show related entries (when grouped or filtered by account)
- [ ] click on an amount would show the related journal entries that justify the amount

Configuration / account list

- [ ] Click on an account (the amount on the right) should redirect to the general ledger filtered on that account and all other filters unset.

**Comment by stxm** [comment]
@akshayitzme Do you see any possibility to merge some of the open PRs?

**Comment by mihir-kandoi** [comment]
Keep this as an umbrella, but its checked boxes do not establish delivery: #1026, #1028, #1029, #1031, and #1032 are still open PRs. Record implementation and release status separately. Concrete General Ledger opening-balance behavior is tracked in #1410, and configurable columns in #724. Unlinked navigation and saved-report requirements should receive focused acceptance criteria.
